### ISSUE TITLE
SMT lecture minor errors

### ISSUE THREAD

**Issue by stanleybak** [sayanmitracode/cpsbooksite#2]
* In the SMT lecture on slide 18 near the middle bullet, you have that {1, -2 or 3, -4, -1 or 2 or 4} is sent to DPLL and it returns {1, 3, -4}. Should this instead be that it returns {1, 2, 3, -4} ? Otherwise, the last clause (-1 or 2 or 4) may not evaluate to true. This will also affect the second-to-last line on what is sent to DPLL in the next round.

* One more change I would suggest is the SMT slides on slide 9 about decision procedures, it says a theory solver takes in a set of literals, which is explained as a set of atomic prepositions in CNF, whereas I think this should just be that the set is interpreted as the conjunction of the literals, not in CNF. If theory solvers worked with CNF directly, then you could skip the SAT solver step altogether and call the theory solver directly (if it involves one theory).

**Comment by sayanmitracode** [comment]
Thanks, these were both correct suggestions. New, fixed versions are uploaded.
